/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Jogo1;

import java.util.Scanner;

public class App {


    public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
    
            System.out.println("Escolha o nome do seu personagem");
            String nomePersonagem = scanner.nextLine();
            
            Espingardeiro espingardeiro = new Espingardeiro();
            Sniper sniper = new Sniper();
            Pistoleiro pistoleiro = new Pistoleiro();
            AtiradorAssalto atiradorAssalto = new AtiradorAssalto();
            
            System.out.println("\nEscolha a sua classe de Personagem:");
            System.out.println("1. Espingardeiro");
            System.out.println("2. Sniper");
            System.out.println("3. Pistoleiro");
            System.out.println("4. Atirador de Assalto");
            int escolha = scanner.nextInt();
            
            Personagem escolhido = null;
            
                 switch (escolha) {
                case 1:
                    escolhido = espingardeiro;
                    break;
                case 2:
                    escolhido = sniper;
                    break;
                case 3:
                    escolhido = pistoleiro;
                    break;
                case 4:
                    escolhido = atiradorAssalto;
                    break;
                    default:
                System.out.println("Opção invalida.");
                return;
            }

         int numero1 = 0;
         int numero2 = 0;
         int numero3 = 0;
         int numero4 = 0;

        if (escolhido instanceof Espingardeiro) {
            numero1 = 3;
            numero2 = 4;
            numero3 = 2;
            numero4 = 1;
        } else if (escolhido instanceof Sniper) {
            numero1 = 4;
            numero2 = 2;
            numero3 = 1;
            numero4 = 3;
        } else if (escolhido instanceof Pistoleiro) {
            numero1 = 2;
            numero2 = 1;
            numero3 = 3;
            numero4 = 4;
        } else if (escolhido instanceof AtiradorAssalto) {
            numero1 = 1;
            numero2 = 3;
            numero3 = 4;
            numero4 = 2;
        }
        
        String palavra1 = (numero1 == 1) ? "dado" : "dados";
        String palavra2 = (numero2 == 1) ? "dado" : "dados";
        String palavra3 = (numero3 == 1) ? "dado" : "dados";
        String palavra4 = (numero4 == 1) ? "dado" : "dados";
    
         /*aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*/
                 
        System.out.println("");
        System.out.println("Agora defina seus atributos rolando os dados!");
        
        System.out.println("Voce tem " + numero1 +" "+ palavra1 + " para o dano");
        Scanner scanner1 = new Scanner(System.in);
        int ArmazenaDano = escolhido.Dano();
        
        System.out.println("Voce quer rolar os dados? (s/n): ");
        String resposta1 = scanner1.nextLine();
        if (resposta1.equals("s")) {
           System.out.println("Dano: " + ArmazenaDano);
        } else {
            System.out.println("Ok, você escolheu nao rolar os dados.");
        }
        System.out.println("");
         /*aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*/
        
          System.out.println("Voce tem " +numero2 +" "+palavra2 + " para a vida");
          Scanner scanner2 = new Scanner(System.in);
        int ArmazenaVida = escolhido.Vida();
          
        System.out.println("Voce quer rolar os dados? (s/n): ");
        String resposta2 = scanner2.nextLine();
        if (resposta2.equals("s")) {
           System.out.println("Vida: " + ArmazenaVida);
        } else {
            System.out.println("Ok, voce escolheu nao rolar os dados.");
        }
        System.out.println("");
        /*aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*/

        System.out.println("Voce tem " + numero3 +" "+ palavra3 + " para a municao");
        Scanner scanner3 = new Scanner(System.in);
        int ArmazenaMana = escolhido.Mana();
        
        System.out.println("Voce quer rolar os dados? (s/n): ");
        String resposta3 = scanner3.nextLine();
        if (resposta3.equals("s")) {
           System.out.println("Municao: " + ArmazenaMana);
        } else {
            System.out.println("Ok, voce escolheu nao rolar os dados.");
        }
       System.out.println("");
        /*aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*/
        
        System.out.println("Voce tem " + numero4 +" "+ palavra4 +" para a agilidade");
        Scanner scanner4 = new Scanner(System.in);
        int ArmazenaAgilidade = escolhido.Agilidade();
        
        System.out.println("Voce quer rolar os dados? (s/n): ");
        String resposta4 = scanner4.nextLine();
        if (resposta4.equals("s")) {
           System.out.println("Agilidade: " + ArmazenaAgilidade);
        } else {
            System.out.println("Ok, voce escolheu nao rolar os dados.");
        }
        System.out.println("");
        /*aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*/
       
        System.out.println("Aqui estao seus atributos:");
        System.out.println("Nome: " + nomePersonagem);
        System.out.println("Dano: " + ArmazenaDano);
        System.out.println("Vida: " + ArmazenaVida);
        System.out.println("Municao: " + ArmazenaMana);
        System.out.println("Agilidade: " + ArmazenaAgilidade);
    }
}