/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Projeto02.view;

import com.example.Projeto02.controller.ProductController;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ScreenSeller extends javax.swing.JFrame {

    private ProductController ProductController;
    DefaultListModel<String> model = new DefaultListModel<>(); // cria um modelo de array list

    /**
     * Creates new form ScreenLogin
     */
    public ScreenSeller() {
        initComponents();
        ProductController = new ProductController();
        ListProducts.setModel(model); // faz a lista virar o modelo criado
        loadProducts();
    }

    private void loadProducts() {
        ArrayList<String> produtos = ProductController.ListProducts();
        model.clear(); // limpa qualquer dado antigo
        for (String produto : produtos) {
            model.addElement(produto); // adiciona todos os produtos
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        ListProducts = new javax.swing.JList<>();
        ButBack = new javax.swing.JButton();
        ButClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtProduct = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButAdd = new javax.swing.JButton();
        ButUpdate = new javax.swing.JButton();
        ButDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtKg = new javax.swing.JTextField();

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButBack.setText("Back");
        ButBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButBackActionPerformed(evt);
            }
        });

        ButClose.setText("Close");
        ButClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCloseActionPerformed(evt);
            }
        });

        jLabel1.setText("Product:");

        txtProduct.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtBrand.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Brand:");

        jLabel3.setText("Value:");

        ButAdd.setText("Add");
        ButAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAddActionPerformed(evt);
            }
        });

        ButUpdate.setText("Update");
        ButUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButUpdateActionPerformed(evt);
            }
        });

        ButDelete.setText("Delete");
        ButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButDeleteActionPerformed(evt);
            }
        });

        jLabel4.setText("Kg");

        txtKg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButBack)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProduct)
                            .addComponent(txtBrand)
                            .addComponent(txtValue)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButClose)
                                .addGap(0, 28, Short.MAX_VALUE)))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(104, 104, 104)
                                .addComponent(txtKg)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(ButDelete))
                    .addComponent(ListProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButBack)
                    .addComponent(ButClose))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ListProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButAdd)
                    .addComponent(ButUpdate)
                    .addComponent(ButDelete))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAddActionPerformed
        // pega os valores escritos pelo usuario
        String newProduct = txtProduct.getText();
        String newValue = txtValue.getText();
        String newBrand = txtBrand.getText();
        String newKg = txtKg.getText();

        // adiciona o produto no banco
        ProductController.registerProduct(newProduct, newValue, newBrand, newKg);

        // atualiza a lista na interface gráfica
        loadProducts(); // recarrega a lista no JList

        // limpa os campos depois de adicionar
        txtProduct.setText("");
        txtBrand.setText("");
        txtValue.setText("");
        txtKg.setText("");
    }//GEN-LAST:event_ButAddActionPerformed

    private void ButUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButUpdateActionPerformed
        // seleciona o id
        String idSelected = ListProducts.getSelectedValue();
        if (idSelected != null) {
            // este comando retorna um array onde o sinal " | " é o separador
            int selected = Integer.parseInt(idSelected.split("\\|")[0].replace("ID:", "").trim());
            // depois seleciona o id do array, tira a string e eremove os espaços

            // pega os valores escritos pelo usuario     
            String newProduct = txtProduct.getText();
            String newValue = txtValue.getText();
            String newBrand = txtBrand.getText();
            String newKg = txtKg.getText();

            // atualiza o produto
            ProductController.updateProduct(newProduct, newValue, newBrand, newKg, selected);

            loadProducts(); // Atualiza a lista na tela
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto para atualizar!");
        }
    }//GEN-LAST:event_ButUpdateActionPerformed

    private void ButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButDeleteActionPerformed
        // seleciona o id
        String idSelected = ListProducts.getSelectedValue();
        if (idSelected != null && idSelected.startsWith("ID: ")) {
            // este comando retorna um array onde o sinal " | " é o separador
            int selected = Integer.parseInt(idSelected.split("\\|")[0].replace("ID:", "").trim());
            // depois seleciona o id do array, tira a string e eremove os espaços          

            // atualiza o produto
            ProductController.deleteProduct(selected);
            loadProducts(); // atualiza o JList depois de deletar
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto para deletar.");
        }
    }//GEN-LAST:event_ButDeleteActionPerformed

    private void ButBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButBackActionPerformed
        new ScreenLogin().setVisible(true); // abre a frame Login
        dispose(); // fecha o frame atual
    }//GEN-LAST:event_ButBackActionPerformed

    private void ButCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCloseActionPerformed
        dispose(); // fecha o frame atual
    }//GEN-LAST:event_ButCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenSeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAdd;
    private javax.swing.JButton ButBack;
    private javax.swing.JButton ButClose;
    private javax.swing.JButton ButDelete;
    private javax.swing.JButton ButUpdate;
    private javax.swing.JList<String> ListProducts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.TextField textField1;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtKg;
    private javax.swing.JTextField txtProduct;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
