/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Projeto02.view;

import com.example.Projeto02.controller.ProductController;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ScreenConsumer extends javax.swing.JFrame {

    private ProductController ProductController;
    DefaultListModel<String> model1 = new DefaultListModel<>();
    DefaultListModel<String> model2 = new DefaultListModel<>();

    /**
     * Creates new form ScreenLogin
     */
    public ScreenConsumer() {
        initComponents();
        ProductController = new ProductController();
        // Define os modelos corretamente para cada lista
        ListProducts.setModel(model1);  // Para exibir os produtos disponíveis
        ListCar.setModel(model2);       // Para exibir os produtos no carrinho

        loadProducts1(); // Carregar produtos em model1
    }

    private void loadProducts1() {
        ArrayList<String> produtos = ProductController.ListProducts();
        model1.clear(); // Limpa qualquer dado antigo
        for (String produto : produtos) {
            model1.addElement(produto); // Adiciona cada produto no modelo do ListProducts
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListProducts = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListCar = new javax.swing.JList<>();
        ButFinish = new javax.swing.JButton();
        ButAdd = new javax.swing.JButton();
        ButRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(ListProducts);

        jScrollPane2.setViewportView(ListCar);

        ButFinish.setText("Finish");
        ButFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButFinishActionPerformed(evt);
            }
        });

        ButAdd.setText("Add");
        ButAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAddActionPerformed(evt);
            }
        });

        ButRemove.setText("Remove");
        ButRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(ButAdd)
                        .addGap(18, 18, 18)
                        .addComponent(ButRemove)
                        .addGap(18, 18, 18)
                        .addComponent(ButFinish)
                        .addGap(0, 124, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButRemove)
                    .addComponent(ButFinish)
                    .addComponent(ButAdd))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int Finish = 0;

    private void ButAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAddActionPerformed
        String idSelected = ListProducts.getSelectedValue();
        if (idSelected != null) {
            int selectedId = Integer.parseInt(idSelected.split("\\|")[0].replace("ID:", "").trim());

            String CarProduct = ListProducts.getSelectedValue();

            if (CarProduct != null) {
                model2.addElement(CarProduct);
                model1.removeElement(CarProduct);
                ProductController.deleteProduct(selectedId);
            }
        }
        loadProducts1();

        Finish = 0;
    }//GEN-LAST:event_ButAddActionPerformed

    private void ButRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButRemoveActionPerformed
        String idSelected = ListCar.getSelectedValue();
        if (idSelected != null) {
            String selectedProduct = idSelected.split("\\|")[1].replace("Product:", "").trim();
            String selectedValue = idSelected.split("\\|")[2].replace("Value:", "").trim();
            String selectedBrand = idSelected.split("\\|")[3].replace("Brand:", "").trim();
            String selectedKg = idSelected.split("\\|")[4].replace("Kg:", "").trim();

            model2.removeElement(idSelected);
            ProductController.registerProduct(selectedProduct, selectedValue, selectedBrand, selectedKg);
            loadProducts1();

            Finish = 0;
        }
    }//GEN-LAST:event_ButRemoveActionPerformed

    private void ButFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButFinishActionPerformed
        Finish = 1;
        JOptionPane.showMessageDialog(null, "Sua compra foi finalizada!");
        new ScreenLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_ButFinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenConsumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenConsumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenConsumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenConsumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenConsumer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAdd;
    private javax.swing.JButton ButFinish;
    private javax.swing.JButton ButRemove;
    private javax.swing.JList<String> ListCar;
    private javax.swing.JList<String> ListProducts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
