/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Aula3;

public class App {
    public static void main(String[] args) {
        Cachorro1 meuCachorro = new Cachorro1("Branco", 10, true, "Carne");
        meuCachorro.exibirAnimal();
        meuCachorro.emitirSom();
        meuCachorro.correr();
        
        Gato1 meuGato = new Gato1("Bege", 6, false, "Peixe");
        meuGato.exibirAnimal();
        meuGato.emitirSom();
        meuGato.comer();
    }
}
