/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package loginEncriptado;

import loginEncriptado.database.Conexao;

public class App {
    
    public static void main(String[] args) {
    Conexao.conectar();
            }
}
