/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Projeto01;

import Projeto01.controller.ProductController;
import Projeto01.database.ConnectionSQL;

public class App {
    public static void main(String[] args) {
        ConnectionSQL.connect();
        
        try {ConnectionSQL.createTables();
        } catch (Exception e) {
        System.out.println("Erro: " + e.getMessage());
        }
        
        ProductController.registerProduct("Arros", 12, "Prato fino", 10);
        // ProductController.updateProduct("Arroz", 12, "Prato Fino", 10, 3);
        // System.out.println(ProductController.deleteProduct(3));
    }
}
