/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TrabalhoArray;
import java.util.ArrayList;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
    int pago = 0;
    
    Scanner scanner = new Scanner(System.in);
    Frutas frutas = new Frutas();
    Vegetais vegetais = new Vegetais();
    Proteinas proteinas = new Proteinas();
    Latcionios laticinios = new Latcionios();
    Carboidratos carboidratos = new Carboidratos();
    Menus menus = new Menus();
        for(int i = 0; pago == 0; i ++){
       // fazer primeiro as opç~es de compra
            System.out.println("Qual tipo de alimento voce deseja comprar: ");            
            System.out.println("1. Frutas");
            System.out.println("2. Vegetais");
            System.out.println("3. Proteinas");
            System.out.println("4. Laticinios");
            System.out.println("5. Carboidratos");
            int escolha = scanner.nextInt();
            
            switch (escolha){
                case 1:
                    System.out.println(menus.Frutasmenu());
                    break;
                case 2:
                    System.out.println(menus.Vegetaismenu());
                    break;
                case 3:
                    System.out.println(menus.Proteinasmenu());
                    break;
                case 4:
                    System.out.println(menus.Laticiniosmenu());
                    break;
                case 5:
                    System.out.println(menus.Carboidratosmenu());
                    break;
                default:  
                    System.out.println("Opcao invalida.");
                    break;
                    
            }
             
    }
}
}
