/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TrabalhoArray2;

class Pokemon {
    private String name;
    private String type;
    private int level;

    // Construtor
    public Pokemon(String name, String type, int level) {
        this.name = name;
        this.type = type;
        this.level = level;
    }

    // Adiciona um metodo para mostrar o pokemon
    public String mostrarPokemon() {
        return "Pokemon: " +name+ ", Type: " +type+ ", level: " +level+ ".";
    }
}