/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TrabalhoArray2;

public class Pokemon {
    public String nome;
    public String tipo;
    public int nivel;
    
     public Pokemon(String nome, String tipo, int nivel) {
        this.nome = nome;
        this.tipo = tipo;
        this.nivel = nivel;
}
}