/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Projeto02;

import com.example.Projeto02.controller.ProductController;
import com.example.Projeto02.database.ConnectionSQL;
import com.example.Projeto02.view.ScreenLogin;

public class App {

    public static void main(String[] args) {
        ConnectionSQL.connect();

        try {
            ConnectionSQL.createTables();
        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
        }

        // ProductController.registerProduct("Arros", 12, "Prato fino", 10);
        // ProductController.updateProduct("Arroz", 12, "Prato Fino", 10, 1);
        // System.out.println(ProductController.deleteProduct(1));
        
        new ScreenLogin().setVisible(true);
    }
}
