/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package teste;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class AppTestTeste {
    @Test 
        public void Soma() {
            Calculadora calculadora = new Calculadora();
            int resultadoesperado = 30;
            int soma = calculadora.soma(10, 20);
            Assertions.assertEquals(resultadoesperado, soma);

    }
    @Test 
        public void Subtracao(){
            Calculadora calculadora = new Calculadora();
            int resultadoesperado = 10;
            int subtracao = calculadora.subtracao(20, 10);
            Assertions.assertEquals(resultadoesperado, subtracao);
    }
    @Test 
        public void Multiplicacao(){
            Calculadora calculadora = new Calculadora();
int resultadoesperado = 4;
int multiplicacao = calculadora.multiplicacao(2, 2);
Assertions.assertEquals(resultadoesperado, multiplicacao);
    }
    @Test
         public void Divisao(){
    Calculadora calculadora = new Calculadora();
int resultadoesperado = 2;
int divisao = calculadora.divisao(20, 10);
Assertions.assertEquals(resultadoesperado, divisao);
    }
}
